# use this file to set the compiler and flags for SYCL
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMPLR_ROOT $ENV{CMPLR_ROOT})
message(STATUS "CMPLR_ROOT: ${CMPLR_ROOT}")
# set(CMAKE_CXX_COMPILER ${CMPLR_ROOT}/bin/icx.exe)
# set(CMAKE_C_COMPILER ${CMPLR_ROOT}/bin/icx.exe)
set(CMAKE_CXX_COMPILER ${CMPLR_ROOT}/bin/icx-cl.exe)
set(CMAKE_C_COMPILER ${CMPLR_ROOT}/bin/icx-cl.exe)
# set(CMAKE_CXX_FLAGS_DEBUG "/Od /Zi")
# set(CMAKE_CXX_FLAGS_RELEASE "/O2")
# set(CMAKE_C_FLAGS_DEBUG "/Od /Zi")
# set(CMAKE_C_FLAGS_RELEASE "/O2")
# set(CMAKE_CXX_COMPILER_WORKS TRUE)
# set(CMAKE_C_COMPILER_WORKS TRUE)
# set(CMAKE_CXX_COMPILER_FORCED TRUE)
# set(CMAKE_C_COMPILER_FORCED TRUE)

set(CMAKE_CXX_COMPILER_ID IntelLLVM)
set(CMAKE_C_COMPILER_ID IntelLLVM)

set(CMAKE_CXX_FLAGS_INIT "/Qstd=c++20 /EHsc")
set(CMAKE_C_FLAGS_INIT "")